baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es"
title = "Intel Center"
theme = "terminal"

# Forzamos que las URLs sean siempre absolutas y correctas
canonifyURLs = true

[pagination]
  pagerSize = 5

[params]
    contentTypeName = "posts"
    # Forzamos el color y el fondo
    themeColor = "orange"
    defaultTheme = "dark"
    centerTheme = true

[menu]
  [[menu.main]]
    name = "Mapa"
    url = "/mapa/"
    weight = 10
  [[menu.main]]
    name = "Informes"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Acerca de"
    url = "/about/"
    weight = 30
  [[menu.main]]
    name = "Contacto"
    url = "/contact/"
    weight = 40
