baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es-es"
title = "El Mapa y El CÃ³digo"
theme = "terminal"

[params]
  customCSS = ["css/custom.css"]
  contentTypeName = "posts"
  placeholderLowResImg = "/img/placeholder.png"
  themeColor = "green"

  [params.terminal]
    showTitlePlaceholder = true
    terminalTitle = "CENTRO_INTEL ~ mcasrom"

[menu]
  [[menu.main]]
    name = "Mapa de Hotspots"
    url = "mapa/"
    weight = 10
  [[menu.main]]
    name = "Informes"
    url = "posts/"
    weight = 20
