baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es-es"
title = "El Mapa y El Código"
theme = "terminal"

[params]
  # Esta es la forma estándar del tema Terminal para cargar CSS extra
  customCSS = ["css/custom.css"]
  themeColor = "green"
  contentTypeName = "posts"

  [params.terminal]
    showTitlePlaceholder = true
    terminalTitle = "CENTRO_INTEL ~ mcasrom"

[menu]
  [[menu.main]]
    name = "Mapa de Hotspots"
    url = "mapa/"
    weight = 10
  [[menu.main]]
    name = "Informes"
    url = "posts/"
    weight = 20
