baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es"
title = "Intel Center"
theme = "terminal"

# Esto evita que Hugo intente ser "inteligente" con las rutas
canonifyURLs = false
relativeURLs = false

[params]
    contentTypeName = "posts"
    themeColor = "orange"
    defaultTheme = "dark"

[menu]
  [[menu.main]]
    name = "Mapa"
    url = "/intel_center/mapa/"
    weight = 10
  [[menu.main]]
    name = "Informes"
    url = "/intel_center/posts/"
    weight = 20
  [[menu.main]]
    name = "Acerca de"
    url = "/intel_center/about/"
    weight = 30
  [[menu.main]]
    name = "Contacto"
    url = "/intel_center/contact/"
    weight = 40
