baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es"
title = "Intel Center"
theme = "PaperMod"

# Esto asegura que los enlaces sean absolutos y no se dupliquen
canonifyURLs = true
relativeURLs = false

[params]
    defaultTheme = "dark"
    showCodeCopyButtons = true

[menu]
    [[menu.main]]
        identifier = "mapa"
        name = "Mapa"
        url = "/mapa/"
        weight = 10
    [[menu.main]]
        identifier = "posts"
        name = "Informes"
        url = "/posts/"
        weight = 20
    [[menu.main]]
        identifier = "about"
        name = "Acerca de"
        url = "/about/"
        weight = 30
    [[menu.main]]
        identifier = "contact"
        name = "Contacto"
        url = "/contact/"
        weight = 40
