baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es"
title = "Intel Center"
theme = "ananke"
enableRobotsTXT = true     # <--- ESTA ES LA MEJORA M1.4
buildFuture = true
buildDrafts = true
canonifyURLs = true
relativeURLs = false

[taxonomies]
  category = "categories"
  tag = "tags"
  report_type = "report_types"

[menu]
  [[menu.main]]
    name = "Mapa"
    url = "/mapa/"
    weight = 10
  
  [[menu.main]]
    name = "Diarios"
    url = "/report_types/diario/"
    weight = 21

  [[menu.main]]
    name = "Semanales"
    url = "/report_types/semanal/"
    weight = 22

  [[menu.main]]
    name = "Mensuales"
    url = "/report_types/mensual/"
    weight = 23

  [[menu.main]]
    name = "Metodología"
    url = "/report_types/metodologia/"
    weight = 30

  [[menu.main]]
    name = "Informes (Todo)"
    url = "/post/"
    weight = 40

  [[menu.main]]
    name = "Arquitectura"
    url = "/arquitectura/"
    weight = 50

  [[menu.main]]
    name = "Acerca de"
    url = "/about/"
    weight = 60

  [[menu.main]]
    name = "Contacto"
    url = "/contact/"
    weight = 70

[params]
  description = "Nodo de inteligencia OSINT - Monitorización global en tiempo real"
  featured_image = "images/header_intel.jpg"
  favicon = "favicon.png"
  site_logo = "favicon.png"
  # CRÍTICO: URL absoluta para og:image en WhatsApp/Telegram
  images = ["https://mcasrom.github.io/intel_center/images/header_intel.jpg"]
