baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es"
title = "Intel Center"
theme = "ananke"

[menu]
  [[menu.main]]
    name = "Mapa"
    url = "/mapa/"
    weight = 10
  [[menu.main]]
    name = "Informes"
    url = "/post/"
    weight = 20
