baseURL = "http://localhost:1313/"
languageCode = "es"
title = "Intel Center"
theme = "terminal"

[pagination]
  pagerSize = 5

[params]
    contentTypeName = "posts"
    centerTheme = true

[menu]
  [[menu.main]]
    name = "Mapa"
    url = "/mapa/"
    weight = 10
  [[menu.main]]
    name = "Informes"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Acerca de"
    url = "/about/"
    weight = 30
  [[menu.main]]
    name = "Contacto"
    url = "/contact/"
    weight = 40
