baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es"
title = "Intel Center"
theme = "ananke"

# Desactivamos las funciones de ayuda de Hugo para que no estorben
canonifyURLs = false
relativeURLs = false

[menu]
  [[menu.main]]
    name = "Mapa"
    url = "https://mcasrom.github.io/intel_center/mapa/"
    weight = 10
  [[menu.main]]
    name = "Informes"
    url = "https://mcasrom.github.io/intel_center/posts/"
    weight = 20
  [[menu.main]]
    name = "Acerca de"
    url = "https://mcasrom.github.io/intel_center/about/"
    weight = 30
  [[menu.main]]
    name = "Contacto"
    url = "https://mcasrom.github.io/intel_center/contact/"
    weight = 40
