baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es"
title = "Intel Center"
theme = "ananke"
buildFuture = true
buildDrafts = true
canonifyURLs = true
relativeURLs = false

[taxonomies]
  category = "categories"
  tag = "tags"
  report_type = "report_types"

[menu]
  [[menu.main]]
    name = "Mapa"
    url = "/mapa/"
    weight = 10
  
  # --- BLOQUE DE FILTRADO INTEL ---
  [[menu.main]]
    name = "Diarios"
    url = "/report_types/diario/"
    weight = 21
  [[menu.main]]
    name = "Semanales"
    url = "/report_types/semanal/"
    weight = 22
  [[menu.main]]
    name = "Mensuales"
    url = "/report_types/mensual/"
    weight = 23
  # --------------------------------

  [[menu.main]]
    name = "Metodolog√≠a"
    url = "/metodologia/"
    weight = 30
  [[menu.main]]
    name = "Informes (Todo)"
    url = "/post/"
    weight = 40
  [[menu.main]]
    name = "Arquitectura"
    url = "/arquitectura/"
    weight = 50
  [[menu.main]]
    name = "Acerca de"
    url = "/about/"
    weight = 60
