baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es"
title = "Intel Center"
theme = "terminal"

# Esto obliga a Hugo a usar la baseURL completa en cada enlace del men√∫
canonifyURLs = true
relativeURLs = false

[params]
    contentTypeName = "posts"
    themeColor = "orange"
    defaultTheme = "dark"

[menu]
  [[menu.main]]
    name = "Mapa"
    url = "mapa/"
    weight = 10
  [[menu.main]]
    name = "Informes"
    url = "posts/"
    weight = 20
  [[menu.main]]
    name = "Acerca de"
    url = "about/"
    weight = 30
  [[menu.main]]
    name = "Contacto"
    url = "contact/"
    weight = 40
