baseURL = "https://mcasrom.github.io/intel_center/"
languageCode = "es"
title = "Intel Center"
theme = "ananke"

[menu]
  [[menu.main]]
    name = "Mapa"
    url = "https://mcasrom.github.io/intel_center/mapa/"
    weight = 10
  [[menu.main]]
    name = "Informes"
    url = "https://mcasrom.github.io/intel_center/posts/"
    weight = 20
  [[menu.main]]
    name = "Acerca de"
    url = "https://mcasrom.github.io/intel_center/about/"
    weight = 30
